# Generated by Django 5.2.1 on 2025-07-13 08:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pedido', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del pedido', verbose_name='Fecha del Pedido')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='pendiente', help_text='Estado actual del procesamiento del pedido', max_length=20, verbose_name='Estado')),
                ('total', models.DecimalField(decimal_places=2, help_text='Monto total del pedido', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total')),
                ('notas', models.TextField(blank=True, help_text='Notas adicionales o instrucciones especiales', verbose_name='Notas')),
                ('usuario', models.ForeignKey(help_text='Usuario que realizó el pedido', on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-fecha_pedido'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre comercial del producto', max_length=100, verbose_name='Nombre del Producto')),
                ('descripcion', models.TextField(help_text='Descripción detallada del producto, características y beneficios', verbose_name='Descripción')),
                ('precio', models.DecimalField(decimal_places=2, help_text='Precio de venta del producto', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Precio')),
                ('stock', models.IntegerField(default=0, help_text='Cantidad disponible en inventario', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock Disponible')),
                ('categoria', models.CharField(help_text='Categoría del producto para organización y filtros', max_length=50, verbose_name='Categoría')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del producto', verbose_name='Fecha de Creación')),
                ('activo', models.BooleanField(default=True, help_text='Determina si el producto está visible y disponible para venta', verbose_name='Producto Activo')),
                ('politicas_envio', models.JSONField(default=dict, help_text='Políticas de envío personalizadas para este producto', verbose_name='Políticas de Envío')),
                ('politicas_devoluciones', models.JSONField(default=dict, help_text='Políticas de devoluciones personalizadas para este producto', verbose_name='Políticas de Devoluciones')),
                ('usuario', models.ForeignKey(help_text='Usuario que creó y gestiona este producto', on_delete=django.db.models.deletion.CASCADE, related_name='productos', to=settings.AUTH_USER_MODEL, verbose_name='Propietario')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ImagenProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(help_text='Archivo de imagen del producto (JPG, PNG, GIF)', upload_to='productos/', verbose_name='Imagen')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de subida de la imagen', verbose_name='Fecha de Subida')),
                ('principal', models.BooleanField(default=False, help_text='Marca esta imagen como la principal del producto', verbose_name='Imagen Principal')),
                ('producto', models.ForeignKey(help_text='Producto al que pertenece esta imagen', on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='productservice.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Imagen de Producto',
                'verbose_name_plural': 'Imágenes de Producto',
                'ordering': ['-principal', '-fecha_subida'],
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre comercial del servicio', max_length=100, verbose_name='Nombre del Servicio')),
                ('descripcion', models.TextField(help_text='Descripción detallada del servicio, qué incluye y beneficios', verbose_name='Descripción')),
                ('precio', models.DecimalField(decimal_places=2, help_text='Precio del servicio', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Precio')),
                ('duracion', models.CharField(help_text="Duración estimada del servicio (ej: '2 horas', '1 semana')", max_length=50, verbose_name='Duración Estimada')),
                ('categoria', models.CharField(help_text='Categoría del servicio para organización y filtros', max_length=50, verbose_name='Categoría')),
                ('imagen', models.ImageField(blank=True, help_text='Imagen principal del servicio (opcional)', null=True, upload_to='servicios/', verbose_name='Imagen Principal')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del servicio', verbose_name='Fecha de Creación')),
                ('activo', models.BooleanField(default=True, help_text='Determina si el servicio está visible y disponible', verbose_name='Servicio Activo')),
                ('politicas_reserva', models.JSONField(default=dict, help_text='Políticas de reserva personalizadas para este servicio', verbose_name='Políticas de Reserva')),
                ('politicas_cancelacion', models.JSONField(default=dict, help_text='Políticas de cancelación personalizadas para este servicio', verbose_name='Políticas de Cancelación')),
                ('usuario', models.ForeignKey(help_text='Usuario que creó y gestiona este servicio', on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to=settings.AUTH_USER_MODEL, verbose_name='Propietario')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ImagenServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(help_text='Archivo de imagen del servicio', upload_to='servicios/', verbose_name='Imagen')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de subida de la imagen', verbose_name='Fecha de Subida')),
                ('principal', models.BooleanField(default=False, help_text='Marca esta imagen como la principal del servicio', verbose_name='Imagen Principal')),
                ('servicio', models.ForeignKey(help_text='Servicio al que pertenece esta imagen', on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='productservice.servicio', verbose_name='Servicio')),
            ],
            options={
                'verbose_name': 'Imagen de Servicio',
                'verbose_name_plural': 'Imágenes de Servicio',
                'ordering': ['-principal', '-fecha_subida'],
            },
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1, help_text='Cantidad solicitada', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, help_text='Precio unitario al momento del pedido', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Precio Unitario')),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='Subtotal de esta línea (cantidad × precio unitario)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Subtotal')),
                ('pedido', models.ForeignKey(help_text='Pedido al que pertenece este detalle', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='productservice.pedido', verbose_name='Pedido')),
                ('producto', models.ForeignKey(blank=True, help_text='Producto solicitado (si aplica)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='productservice.producto', verbose_name='Producto')),
                ('servicio', models.ForeignKey(blank=True, help_text='Servicio solicitado (si aplica)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='productservice.servicio', verbose_name='Servicio')),
            ],
            options={
                'verbose_name': 'Detalle de Pedido',
                'verbose_name_plural': 'Detalles de Pedido',
            },
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['usuario', 'estado'], name='productserv_usuario_3f80ce_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['fecha_pedido'], name='productserv_fecha_p_e679b9_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['estado'], name='productserv_estado_3ddc4f_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['usuario', 'activo'], name='productserv_usuario_7344a2_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['categoria'], name='productserv_categor_a42f2c_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['fecha_creacion'], name='productserv_fecha_c_f4adc9_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['precio'], name='productserv_precio_546856_idx'),
        ),
        migrations.AddIndex(
            model_name='imagenproducto',
            index=models.Index(fields=['producto', 'principal'], name='productserv_product_3d28e4_idx'),
        ),
        migrations.AddIndex(
            model_name='imagenproducto',
            index=models.Index(fields=['fecha_subida'], name='productserv_fecha_s_c4fb6c_idx'),
        ),
        migrations.AddIndex(
            model_name='servicio',
            index=models.Index(fields=['usuario', 'activo'], name='productserv_usuario_588efa_idx'),
        ),
        migrations.AddIndex(
            model_name='servicio',
            index=models.Index(fields=['categoria'], name='productserv_categor_9641a7_idx'),
        ),
        migrations.AddIndex(
            model_name='servicio',
            index=models.Index(fields=['fecha_creacion'], name='productserv_fecha_c_817515_idx'),
        ),
        migrations.AddIndex(
            model_name='servicio',
            index=models.Index(fields=['precio'], name='productserv_precio_a1fea8_idx'),
        ),
        migrations.AddIndex(
            model_name='imagenservicio',
            index=models.Index(fields=['servicio', 'principal'], name='productserv_servici_f63989_idx'),
        ),
        migrations.AddIndex(
            model_name='imagenservicio',
            index=models.Index(fields=['fecha_subida'], name='productserv_fecha_s_825dce_idx'),
        ),
        migrations.AddIndex(
            model_name='detallepedido',
            index=models.Index(fields=['pedido'], name='productserv_pedido__af8b35_idx'),
        ),
        migrations.AddIndex(
            model_name='detallepedido',
            index=models.Index(fields=['producto'], name='productserv_product_b92a2c_idx'),
        ),
        migrations.AddIndex(
            model_name='detallepedido',
            index=models.Index(fields=['servicio'], name='productserv_servici_4fcd98_idx'),
        ),
    ]
