# Generated by Django 5.2.1 on 2025-07-23 00:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productservice', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='empresa',
            field=models.ForeignKey(default=1, help_text='Empresa que debe procesar este pedido', on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_recibidos', to=settings.AUTH_USER_MODEL, verbose_name='Empresa Destinataria'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['empresa', 'estado'], name='productserv_empresa_637af9_idx'),
        ),
    ]
