# Generated by Django 5.2.1 on 2025-11-10 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productservice', '0002_add_empresa_to_pedido'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MensajePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField(help_text='Contenido del mensaje', verbose_name='Mensaje')),
                ('archivo_adjunto', models.FileField(blank=True, help_text='Archivo adjunto al mensaje (imagen, PDF, etc.)', null=True, upload_to='mensajes_pedidos/%Y/%m/%d/', verbose_name='Archivo Adjunto')),
                ('leido', models.BooleanField(default=False, help_text='Indica si el mensaje ha sido leído por el destinatario', verbose_name='Leído')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de envío del mensaje', verbose_name='Fecha de Envío')),
                ('pedido', models.ForeignKey(help_text='Pedido sobre el que se está comunicando', on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='productservice.pedido', verbose_name='Pedido')),
                ('remitente', models.ForeignKey(help_text='Usuario que envía el mensaje', on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_enviados', to=settings.AUTH_USER_MODEL, verbose_name='Remitente')),
            ],
            options={
                'verbose_name': 'Mensaje de Pedido',
                'verbose_name_plural': 'Mensajes de Pedidos',
                'ordering': ['fecha_creacion'],
                'indexes': [models.Index(fields=['pedido', 'fecha_creacion'], name='productserv_pedido__2d44cb_idx'), models.Index(fields=['remitente', 'leido'], name='productserv_remiten_1f53e7_idx')],
            },
        ),
    ]
