# Generated by Django 5.2.4 on 2025-11-10 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productservice', '0003_mensajepedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajepedido',
            name='mensaje',
            field=models.TextField(blank=True, help_text='Contenido del mensaje (opcional si hay archivo adjunto)', verbose_name='Mensaje'),
        ),
    ]
