# Generated by Django 6.0 on 2025-12-11 18:31

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productservice', '0004_alter_mensajepedido_mensaje'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservaServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reserva', models.DateTimeField(help_text='Fecha y hora programada para la ejecución del servicio', verbose_name='Fecha y Hora de la Reserva')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación de la reserva', verbose_name='Fecha de Creación')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('en_proceso', 'En Proceso'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='pendiente', help_text='Estado actual de la reserva', max_length=20, verbose_name='Estado')),
                ('precio_total', models.DecimalField(blank=True, decimal_places=2, help_text='Precio total de la reserva (se establece automáticamente desde el servicio)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio Total')),
                ('telefono_contacto', models.CharField(blank=True, help_text='Teléfono de contacto para la reserva', max_length=20, verbose_name='Teléfono de Contacto')),
                ('direccion_servicio', models.TextField(blank=True, help_text='Dirección donde se ejecutará el servicio (si aplica)', verbose_name='Dirección del Servicio')),
                ('notas', models.TextField(blank=True, help_text='Notas adicionales, instrucciones especiales o requisitos', verbose_name='Notas')),
                ('empresa', models.ForeignKey(help_text='Empresa que debe ejecutar este servicio', on_delete=django.db.models.deletion.CASCADE, related_name='reservas_recibidas', to=settings.AUTH_USER_MODEL, verbose_name='Empresa Proveedora')),
                ('pedido_asociado', models.ForeignKey(blank=True, help_text='Pedido asociado a esta reserva (si aplica)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas_asociadas', to='productservice.pedido', verbose_name='Pedido Asociado')),
                ('servicio', models.ForeignKey(help_text='Servicio que se está reservando', on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='productservice.servicio', verbose_name='Servicio')),
                ('usuario', models.ForeignKey(help_text='Usuario que realizó la reserva', on_delete=django.db.models.deletion.CASCADE, related_name='reservas_servicios', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Reserva de Servicio',
                'verbose_name_plural': 'Reservas de Servicios',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['usuario', 'estado'], name='productserv_usuario_ebbeb5_idx'), models.Index(fields=['empresa', 'estado'], name='productserv_empresa_d8c30b_idx'), models.Index(fields=['servicio', 'fecha_reserva'], name='productserv_servici_efc9f1_idx'), models.Index(fields=['fecha_reserva'], name='productserv_fecha_r_d63809_idx'), models.Index(fields=['estado'], name='productserv_estado_1ae996_idx')],
            },
        ),
    ]
