# Generated by Django 5.2.1 on 2025-06-05 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_landingpage_descripcion_landingpage_plantilla'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='hero_image_file',
            field=models.ImageField(blank=True, help_text='Archivo de imagen para la cabecera (alternativo a URL)', null=True, upload_to='landing_hero/'),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='contenido',
            field=models.TextField(blank=True, help_text='texto enriquecido para la sección principal'),
        ),
    ]
