# Generated by Django 5.2.1 on 2025-06-16 00:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_landingpage_hero_image_file_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='landingpage',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Landing Page', 'verbose_name_plural': 'Landing Pages'},
        ),
        migrations.AlterModelOptions(
            name='perfilusuario',
            options={'verbose_name': 'Perfil de Usuario', 'verbose_name_plural': 'Perfiles de Usuario'},
        ),
        migrations.AlterModelOptions(
            name='suscripcion',
            options={'ordering': ['-fecha_inicio'], 'verbose_name': 'Suscripción', 'verbose_name_plural': 'Suscripciones'},
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='color_scheme',
            field=models.CharField(default='default', help_text='Esquema de colores para personalizar la apariencia', max_length=50, verbose_name='Esquema de Colores'),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='contenido',
            field=models.TextField(blank=True, help_text='Contenido principal de la página (acepta HTML básico)', verbose_name='Contenido Principal'),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción o slogan de la empresa', verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha de creación de la landing page', verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='hero_image',
            field=models.URLField(blank=True, help_text='URL de imagen externa para la cabecera', null=True, verbose_name='URL de Imagen Hero'),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='hero_image_file',
            field=models.ImageField(blank=True, help_text='Archivo de imagen subido para la cabecera (tiene prioridad sobre URL)', null=True, upload_to='landing_hero/', verbose_name='Archivo de Imagen Hero'),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='plantilla',
            field=models.CharField(choices=[('plantilla1', 'Plantilla Clásica'), ('plantilla2', 'Plantilla Moderna')], default='plantilla1', help_text='Diseño visual de la landing page', max_length=50, verbose_name='Plantilla de Diseño'),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='titulo',
            field=models.CharField(help_text='Título principal que aparecerá en la página', max_length=200, verbose_name='Título Principal'),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='usuario',
            field=models.ForeignKey(help_text='Usuario propietario de la landing page', on_delete=django.db.models.deletion.CASCADE, related_name='landing_pages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='direccion',
            field=models.TextField(help_text='Dirección completa del usuario o empresa', verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='empresa',
            field=models.CharField(blank=True, help_text='Nombre de la empresa (requerido para cuentas empresariales)', max_length=100, verbose_name='Nombre de la Empresa'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='estado_suscripcion',
            field=models.CharField(choices=[('activa', 'Activa'), ('inactiva', 'Inactiva'), ('vencida', 'Vencida')], default='inactiva', help_text='Estado actual de la suscripción del usuario', max_length=10, verbose_name='Estado de Suscripción'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del perfil', verbose_name='Fecha de Registro'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='fecha_vencimiento',
            field=models.DateTimeField(blank=True, help_text='Fecha de vencimiento de la suscripción actual', null=True, verbose_name='Fecha de Vencimiento'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='permisos',
            field=models.CharField(choices=[('Usuario', 'Usuario'), ('Administrador', 'Administrador')], default='Usuario', help_text='Nivel de permisos dentro de la aplicación', max_length=20, verbose_name='Nivel de Permisos'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='telefono',
            field=models.CharField(help_text='Número de teléfono de contacto', max_length=15, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='tipo_cuenta',
            field=models.CharField(choices=[('empresa', 'Empresa'), ('usuario', 'Usuario')], default='usuario', help_text='Determina si es una cuenta empresarial o de consumidor final', max_length=10, verbose_name='Tipo de Cuenta'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='usuario',
            field=models.OneToOneField(help_text='Usuario de Django asociado a este perfil', on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='suscripcion',
            name='activa',
            field=models.BooleanField(default=True, help_text='Indica si la suscripción está activa', verbose_name='Activa'),
        ),
        migrations.AlterField(
            model_name='suscripcion',
            name='fecha_inicio',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha de inicio de la suscripción', verbose_name='Fecha de Inicio'),
        ),
        migrations.AlterField(
            model_name='suscripcion',
            name='fecha_vencimiento',
            field=models.DateTimeField(help_text='Fecha de vencimiento de la suscripción', verbose_name='Fecha de Vencimiento'),
        ),
        migrations.AlterField(
            model_name='suscripcion',
            name='plan',
            field=models.CharField(choices=[('basico', 'Básico'), ('premium', 'Premium'), ('empresarial', 'Empresarial')], help_text='Tipo de plan de suscripción', max_length=20, verbose_name='Plan'),
        ),
        migrations.AlterField(
            model_name='suscripcion',
            name='precio',
            field=models.DecimalField(decimal_places=2, help_text='Precio pagado por la suscripción', max_digits=10, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='suscripcion',
            name='usuario',
            field=models.ForeignKey(help_text='Usuario propietario de la suscripción', on_delete=django.db.models.deletion.CASCADE, related_name='suscripciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='landingpage',
            index=models.Index(fields=['usuario'], name='accounts_la_usuario_83396b_idx'),
        ),
        migrations.AddIndex(
            model_name='landingpage',
            index=models.Index(fields=['plantilla'], name='accounts_la_plantil_b48c1c_idx'),
        ),
        migrations.AddIndex(
            model_name='perfilusuario',
            index=models.Index(fields=['tipo_cuenta'], name='accounts_pe_tipo_cu_26eee0_idx'),
        ),
        migrations.AddIndex(
            model_name='perfilusuario',
            index=models.Index(fields=['estado_suscripcion'], name='accounts_pe_estado__07cac9_idx'),
        ),
        migrations.AddIndex(
            model_name='perfilusuario',
            index=models.Index(fields=['permisos'], name='accounts_pe_permiso_578d26_idx'),
        ),
        migrations.AddIndex(
            model_name='suscripcion',
            index=models.Index(fields=['usuario', 'activa'], name='accounts_su_usuario_8f5460_idx'),
        ),
        migrations.AddIndex(
            model_name='suscripcion',
            index=models.Index(fields=['plan'], name='accounts_su_plan_ce0e85_idx'),
        ),
        migrations.AddIndex(
            model_name='suscripcion',
            index=models.Index(fields=['fecha_vencimiento'], name='accounts_su_fecha_v_738100_idx'),
        ),
    ]
