# Generated by Django 5.2.4 on 2025-11-24 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_landingpage_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LandingPage',
        ),
    ]
