# Generated by Django 5.2.4 on 2025-11-24 15:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título principal que aparecerá en la página', max_length=200, verbose_name='Título Principal')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción o slogan de la empresa', verbose_name='Descripción')),
                ('hero_image', models.URLField(blank=True, help_text='URL de imagen externa para la cabecera', null=True, verbose_name='URL de Imagen Hero')),
                ('hero_image_file', models.ImageField(blank=True, help_text='Archivo de imagen subido para la cabecera (tiene prioridad sobre URL)', null=True, upload_to='landing_hero/', verbose_name='Archivo de Imagen Hero')),
                ('contenido', models.TextField(blank=True, help_text='Contenido principal de la página (acepta HTML básico)', verbose_name='Contenido Principal')),
                ('plantilla', models.CharField(choices=[('plantilla1', 'Plantilla Clásica'), ('plantilla2', 'Plantilla Moderna')], default='plantilla1', help_text='Diseño visual de la landing page', max_length=50, verbose_name='Plantilla de Diseño')),
                ('color_scheme', models.CharField(default='default', help_text='Esquema de colores para personalizar la apariencia', max_length=50, verbose_name='Esquema de Colores')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha de creación de la landing page', verbose_name='Fecha de Creación')),
                ('usuario', models.ForeignKey(help_text='Usuario propietario de la landing page', on_delete=django.db.models.deletion.CASCADE, related_name='landing_pages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Landing Page',
                'verbose_name_plural': 'Landing Pages',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['usuario'], name='webpages_la_usuario_384f1f_idx'), models.Index(fields=['plantilla'], name='webpages_la_plantil_ea49f5_idx')],
            },
        ),
    ]
