# Generated by Django 5.2.1 on 2025-11-24 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='color_primario',
            field=models.CharField(blank=True, default='#2563eb', help_text='Color primario en formato HEX (ej: #2563eb)', max_length=7, verbose_name='Color Primario'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='color_secundario',
            field=models.CharField(blank=True, default='#22c55e', help_text='Color secundario en formato HEX (ej: #22c55e)', max_length=7, verbose_name='Color Secundario'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='seccion_contacto_boton_texto',
            field=models.CharField(blank=True, default='Contáctanos', help_text='Texto del botón de contacto', max_length=50, verbose_name='Texto Botón Contacto'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='seccion_contacto_boton_url',
            field=models.CharField(blank=True, help_text='URL del botón de contacto', max_length=200, verbose_name='URL Botón Contacto'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='seccion_contacto_texto',
            field=models.TextField(blank=True, help_text='Texto de la sección de contacto o llamada a la acción', verbose_name='Texto Contacto'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='seccion_contacto_titulo',
            field=models.CharField(blank=True, default='¿Listo para comenzar?', help_text='Título para la sección de contacto o CTA final', max_length=200, verbose_name='Título Contacto'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='seccion_productos_subtitulo',
            field=models.CharField(blank=True, help_text='Subtítulo o descripción para la sección de productos', max_length=300, verbose_name='Subtítulo Sección Productos'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='seccion_productos_titulo',
            field=models.CharField(blank=True, default='Nuestros Productos', help_text='Título personalizado para la sección de productos', max_length=200, verbose_name='Título Sección Productos'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='seccion_servicios_subtitulo',
            field=models.CharField(blank=True, help_text='Subtítulo o descripción para la sección de servicios', max_length=300, verbose_name='Subtítulo Sección Servicios'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='seccion_servicios_titulo',
            field=models.CharField(blank=True, default='Nuestros Servicios', help_text='Título personalizado para la sección de servicios', max_length=200, verbose_name='Título Sección Servicios'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='seccion_sobre_nosotros_texto',
            field=models.TextField(blank=True, help_text='Texto descriptivo para la sección "Sobre Nosotros"', verbose_name='Texto Sobre Nosotros'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='seccion_sobre_nosotros_titulo',
            field=models.CharField(blank=True, default='Sobre Nosotros', help_text='Título personalizado para la sección "Sobre Nosotros"', max_length=200, verbose_name='Título Sobre Nosotros'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='seccion_testimonios_texto',
            field=models.TextField(blank=True, help_text='Testimonios o reseñas de clientes (acepta HTML)', verbose_name='Texto Testimonios'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='seccion_testimonios_titulo',
            field=models.CharField(blank=True, default='Lo que dicen nuestros clientes', help_text='Título para la sección de testimonios', max_length=200, verbose_name='Título Testimonios'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='subtitulo_hero',
            field=models.CharField(blank=True, help_text='Subtítulo adicional para la sección hero (opcional)', max_length=300, verbose_name='Subtítulo Hero'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='texto_boton_hero',
            field=models.CharField(blank=True, default='Ver Catálogo', help_text='Texto del botón CTA en el hero', max_length=50, verbose_name='Texto Botón Hero'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='url_boton_hero',
            field=models.CharField(blank=True, help_text='URL del botón CTA (ej: /products/productos/)', max_length=200, verbose_name='URL Botón Hero'),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='plantilla',
            field=models.CharField(choices=[('plantilla1', 'Plantilla Clásica'), ('plantilla2', 'Plantilla Moderna'), ('plantilla3', 'Plantilla Corporativa'), ('plantilla4', 'Plantilla Minimalista')], default='plantilla1', help_text='Diseño visual de la landing page', max_length=50, verbose_name='Plantilla de Diseño'),
        ),
    ]
