# Generated by Django 5.2.4 on 2025-11-24 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0002_landingpage_color_primario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingpage',
            name='plantilla',
            field=models.CharField(choices=[('plantilla1', 'Plantilla Clásica (FREE)'), ('plantilla2', 'Plantilla Moderna (FREE)'), ('plantilla3', 'Plantilla Corporativa (PREMIUM)'), ('plantilla4', 'Plantilla Minimalista (PREMIUM)'), ('plantilla5', 'Plantilla Tech (PREMIUM)'), ('plantilla6', 'Plantilla Autos (PREMIUM)'), ('plantilla7', 'Plantilla Motos (PREMIUM)')], default='plantilla1', help_text='Diseño visual de la landing page', max_length=50, verbose_name='Plantilla de Diseño'),
        ),
    ]
