"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
try:
    import dj_database_url 
except ImportError:
    dj_database_url = None

# Cargar variables de entorno desde .env
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# Define la ruta base del proyecto para referencias relativas
BASE_DIR = Path(__file__).resolve().parent.parent

# Detectar entorno de deployment
IS_RAILWAY = os.getenv('RAILWAY_ENVIRONMENT') is not None
ENVIRONMENT = os.getenv('ENVIRONMENT', 'development').lower()
IS_PRODUCTION = ENVIRONMENT == 'production'
IS_STAGING = ENVIRONMENT == 'staging' or IS_RAILWAY  # Railway se considera staging/testeo

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Clave secreta para la seguridad de la aplicación - ¡IMPORTANTE! Cambiar en producción
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-@0gnsofvzar8!3#ecs+-_1h9=_4a#c5w297&k%bbh(45)o&wpk')

# SECURITY WARNING: don't run with debug turned on in production!
# Modo debug: True para desarrollo y staging (testeo), False solo para producción
DEBUG = os.getenv('DEBUG', 'True' if not IS_PRODUCTION else 'False').lower() == 'true'

# ALLOWED_HOSTS: Configuración según entorno
# NOTA: Django NO acepta wildcards (*.railway.app), necesita dominios exactos
if IS_STAGING or IS_PRODUCTION:
    ALLOWED_HOSTS = []
    
    # Agregar dominio de Railway si está disponible
    railway_domain = os.getenv('RAILWAY_PUBLIC_DOMAIN', '')
    if railway_domain:
        # Remover https:// si está presente (ALLOWED_HOSTS no acepta protocolo)
        railway_domain_clean = railway_domain.replace('https://', '').replace('http://', '')
        ALLOWED_HOSTS.append(railway_domain_clean)
    
    # Agregar dominios personalizados desde variable de entorno
    # Formato: ALLOWED_HOSTS=dominio1.com,www.dominio1.com,dominio2.com
    custom_hosts = os.getenv('ALLOWED_HOSTS', '')
    if custom_hosts:
        # Remover protocolos si están presentes
        hosts_list = [h.strip().replace('https://', '').replace('http://', '') 
                     for h in custom_hosts.split(',') if h.strip()]
        ALLOWED_HOSTS.extend(hosts_list)
    
    # Agregar dominio personalizado teomanager.com si no está en la lista
    if 'teomanager.com' not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append('teomanager.com')
        ALLOWED_HOSTS.append('www.teomanager.com')
    
    # Agregar dominio de Railway específico si existe (fallback)
    # Esto asegura que el dominio de Railway funcione incluso si RAILWAY_PUBLIC_DOMAIN no está configurado
    railway_specific = os.getenv('RAILWAY_DOMAIN', 'web-production-8666.up.railway.app')
    if railway_specific and railway_specific not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(railway_specific)
    
    # Filtrar valores vacíos y duplicados
    ALLOWED_HOSTS = list(set([host for host in ALLOWED_HOSTS if host]))
    
    # Si no hay hosts configurados, permitir todos (solo para testeo)
    if not ALLOWED_HOSTS:
        ALLOWED_HOSTS = ['*']
else:
    ALLOWED_HOSTS = ['*']

# CSRF_TRUSTED_ORIGINS: Orígenes confiables para CSRF
# Django requiere que los orígenes estén en formato completo (con https://)
# NOTA: Django NO acepta wildcards, necesita dominios exactos
def normalize_csrf_origin(origin):
    """Normaliza un origen CSRF para asegurar que tenga el formato correcto."""
    if not origin:
        return origin
    
    origin = origin.strip()
    
    # Remover todas las ocurrencias de protocolos para empezar limpio
    origin = origin.replace('https://', '').replace('http://', '')
    origin = origin.replace('https:/', '').replace('http:/', '')
    
    # Remover barras iniciales y finales
    origin = origin.lstrip('/').rstrip('/')
    
    # Agregar https:// al inicio (siempre usar https en producción)
    origin = f'https://{origin}'
    
    return origin

if IS_STAGING or IS_PRODUCTION:
    CSRF_TRUSTED_ORIGINS = []
    
    # Dominios que SIEMPRE deben estar incluidos
    required_origins = [
        'https://web-production-8666.up.railway.app',  # Dominio de Railway por defecto
        'https://teomanager.com',  # Dominio personalizado
        'https://www.teomanager.com',  # Variante www
    ]
    
    # Agregar dominios requeridos primero
    for origin in required_origins:
        normalized = normalize_csrf_origin(origin)
        if normalized not in CSRF_TRUSTED_ORIGINS:
            CSRF_TRUSTED_ORIGINS.append(normalized)
    
    # Agregar dominio de Railway desde variable automática si está disponible
    railway_domain = os.getenv('RAILWAY_PUBLIC_DOMAIN', '')
    if railway_domain:
        normalized = normalize_csrf_origin(railway_domain)
        if normalized not in CSRF_TRUSTED_ORIGINS:
            CSRF_TRUSTED_ORIGINS.append(normalized)
    
    # Agregar dominio de Railway desde RAILWAY_DOMAIN si está disponible
    railway_specific = os.getenv('RAILWAY_DOMAIN', '')
    if railway_specific:
        # Construir URL completa (normalize_csrf_origin ya agrega https://)
        railway_url = normalize_csrf_origin(railway_specific)
        if railway_url not in CSRF_TRUSTED_ORIGINS:
            CSRF_TRUSTED_ORIGINS.append(railway_url)
    
    # Agregar dominios desde variable de entorno personalizada si existe
    # Formato: CSRF_TRUSTED_ORIGINS=https://dominio1.com,https://dominio2.com
    custom_origins = os.getenv('CSRF_TRUSTED_ORIGINS', '')
    if custom_origins:
        for origin in custom_origins.split(','):
            origin = origin.strip()
            if origin:
                normalized = normalize_csrf_origin(origin)
                if normalized not in CSRF_TRUSTED_ORIGINS:
                    CSRF_TRUSTED_ORIGINS.append(normalized)
    
    # Remover duplicados manteniendo el orden (ya están normalizados)
    CSRF_TRUSTED_ORIGINS = list(dict.fromkeys(CSRF_TRUSTED_ORIGINS))
    
    # Debug: imprimir orígenes configurados (solo en staging para debugging)
    if IS_STAGING:
        print(f"🔒 CSRF_TRUSTED_ORIGINS configurados: {CSRF_TRUSTED_ORIGINS}")
else:
    # En desarrollo, permitir localhost
    CSRF_TRUSTED_ORIGINS = [
        'http://localhost:8000',
        'http://127.0.0.1:8000',
        'http://localhost:5490',
    ]


# Application definition

# Lista de aplicaciones instaladas en el proyecto
INSTALLED_APPS = [
    'django.contrib.admin',  # Panel de administración
    'django.contrib.auth',   # Sistema de autenticación
    'django.contrib.contenttypes',  # Framework de tipos de contenido
    'django.contrib.sessions',  # Framework de sesiones
    'django.contrib.messages',  # Framework de mensajes
    'django.contrib.staticfiles',  # Manejo de archivos estáticos
    'django.contrib.sites',  # Framework de Sites para dominios múltiples
    'apps.accounts',  # Aplicación de cuentas de usuario
    'apps.productservice',  # Aplicación de productos y servicios
    'apps.webpages',  # Aplicación de landing pages y plantillas web
]

# Middleware - Componentes que procesan las peticiones/respuestas
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',  # Seguridad
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Servir archivos estáticos en producción
    'django.contrib.sessions.middleware.SessionMiddleware',  # Manejo de sesiones
    'django.middleware.common.CommonMiddleware',  # Funcionalidades comunes
    'django.middleware.csrf.CsrfViewMiddleware',  # Protección CSRF
    'django.contrib.auth.middleware.AuthenticationMiddleware',  # Autenticación
    'django.contrib.messages.middleware.MessageMiddleware',  # Mensajes
    'django.middleware.clickjacking.XFrameOptionsMiddleware',  # Protección clickjacking
]

# Configuración de URLs principal
ROOT_URLCONF = 'core.urls'

# Configuración de templates
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # Directorio de templates globales
        'APP_DIRS': True,  # Buscar templates en apps
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'apps.accounts.context_processors.user_profile',  # Context processor para perfil global
            ],
        },
    },
]

# Configuración de WSGI
WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Configuración de base de datos: Local (SQLite) o Railway (PostgreSQL)
# Para usar base de datos LOCAL: En .env poner USE_LOCAL_DB=True
# Para usar base de datos RAILWAY: En .env poner USE_LOCAL_DB=False o no poner la variable
USE_LOCAL_DB = os.getenv('USE_LOCAL_DB', 'False').lower() == 'true'

if USE_LOCAL_DB:
    # Base de datos local SQLite (desarrollo)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
    print("✅ Usando base de datos LOCAL (SQLite)")
else:
    # Base de datos PostgreSQL en Railway (producción/staging)
    DATABASE_URL = os.getenv('DATABASE_URL')
    
    if DATABASE_URL:
        # Railway proporciona DATABASE_URL automáticamente cuando conectas PostgreSQL
        if dj_database_url is None:
            raise ImportError("dj-database-url no está instalado. Ejecuta: pip install dj-database-url")
        DATABASES = {
            'default': dj_database_url.parse(DATABASE_URL, conn_max_age=600)
        }
        print("✅ Usando base de datos RAILWAY (PostgreSQL) - DATABASE_URL")
    else:
        # Fallback a variables individuales de PostgreSQL
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.postgresql',
                'NAME': os.getenv('PGDATABASE', 'railway'),
                'USER': os.getenv('PGUSER', 'postgres'),
                'PASSWORD': os.getenv('PGPASSWORD', ''),
                'HOST': os.getenv('PGHOST', 'mainline.proxy.rlwy.net'),
                'PORT': os.getenv('PGPORT', '54586'),
                'OPTIONS': {
                    'connect_timeout': 10,
                },
            }
        }
        print("✅ Usando base de datos RAILWAY (PostgreSQL) - Variables individuales")


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

# Validadores de contraseñas
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

# Configuración de internacionalización
LANGUAGE_CODE = 'en-us'  # Idioma por defecto
TIME_ZONE = 'UTC'  # Zona horaria
USE_I18N = True  # Internacionalización
USE_TZ = True  # Soporte para zonas horarias


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# Configuración de archivos estáticos
STATIC_URL = '/static/'  # URL base para archivos estáticos
STATICFILES_DIRS = [
    BASE_DIR / "static",  # Directorio de archivos estáticos
]
STATIC_ROOT = BASE_DIR / 'staticfiles'  # Directorio para archivos estáticos recolectados

# Configuración de WhiteNoise para producción/staging
if IS_STAGING or IS_PRODUCTION:
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
    
    # Configuraciones de seguridad para producción (solo en producción real)
    if IS_PRODUCTION:
        SECURE_SSL_REDIRECT = True
        SESSION_COOKIE_SECURE = True
        CSRF_COOKIE_SECURE = True
        SECURE_BROWSER_XSS_FILTER = True
        SECURE_CONTENT_TYPE_NOSNIFF = True
        X_FRAME_OPTIONS = 'DENY'
        SECURE_HSTS_SECONDS = 31536000
        SECURE_HSTS_INCLUDE_SUBDOMAINS = True
        SECURE_HSTS_PRELOAD = True

# Configuración de archivos media (subidos por usuarios)
MEDIA_URL = '/media/'  # URL base para archivos media

# Configuración de MEDIA_ROOT según el entorno
# En Railway, usar el volumen persistente si está configurado
# Railway monta volúmenes en /data por defecto
RAILWAY_VOLUME_MOUNT = os.getenv('RAILWAY_VOLUME_MOUNT_PATH', '/data')
USE_RAILWAY_VOLUME = os.getenv('USE_RAILWAY_VOLUME', 'False').lower() == 'true'

if IS_RAILWAY and USE_RAILWAY_VOLUME:
    # Usar volumen persistente de Railway para media
    # El volumen debe estar montado en /data/media
    MEDIA_ROOT = Path(RAILWAY_VOLUME_MOUNT) / 'media'
    print(f"✅ Usando VOLUMEN PERSISTENTE de Railway para media: {MEDIA_ROOT}")
else:
    # Usar directorio local (desarrollo o sin volumen)
    MEDIA_ROOT = BASE_DIR / 'media'
    print(f"✅ Usando directorio LOCAL para media: {MEDIA_ROOT}")

# Asegurarse que el directorio media existe
if not os.path.exists(MEDIA_ROOT):
    os.makedirs(MEDIA_ROOT, exist_ok=True)

# Configuración del campo primario por defecto
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# URLs de redirección después de login/logout
LOGIN_REDIRECT_URL = 'home'  # Redirección después del login
LOGOUT_REDIRECT_URL = 'login'  # Redirección después del logout

# Configuración de correo electrónico
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'  # Solo para desarrollo
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'  # Backend SMTP para producción
EMAIL_HOST = 'smtp.gmail.com'  # Servidor SMTP
EMAIL_PORT = 587  # Puerto SMTP
EMAIL_USE_TLS = True  # Usar TLS para seguridad
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', 'vctechmx@gmail.com')  # Usuario SMTP
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', 'vycyysxlyrildgot')  # Contraseña SMTP
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'TEOmanager <vctechmx@gmail.com>')  # Remitente por defecto

# Configuración de dominio del sitio para emails y enlaces
# Django Sites Framework - ID del sitio (por defecto 1)
SITE_ID = 1

# URL base del sitio para emails (sin barra final)
# Se usa como fallback si Sites Framework no está configurado
SITE_URL = os.getenv('SITE_URL', None)
if not SITE_URL:
    if IS_PRODUCTION:
        SITE_URL = 'https://teomanager.com'
    elif IS_STAGING or IS_RAILWAY:
        # En Railway, usar el dominio personalizado si existe, sino el de Railway
        custom_domain = os.getenv('RAILWAY_PUBLIC_DOMAIN', '')
        if custom_domain:
            SITE_URL = f"https://{custom_domain.replace('https://', '').replace('http://', '')}"
        else:
            railway_domain = os.getenv('RAILWAY_DOMAIN', 'web-production-8666.up.railway.app')
            SITE_URL = f"https://{railway_domain}"
    else:
        SITE_URL = 'http://localhost:5490'
